export var l = [
    {
        restaurant : "食事",
        cafe : "カフェ",
        bar : "居酒屋",
        hotel : "宿泊",
        other : "その他",
        check : "お気に入りリスト",
        history : "屋台の歴史",
        root1 : "呉市の歴史を巡るコース",
        root2 : "居酒屋○次会コース（中通り内回り）",
        root3 : "夜のカフェバー巡りコース",
        search : "検索",
        sByText : "文字入力で探す",
        sByHash : "ハッシュタグから探す",
        sByRec : "あなたへのおすすめ",
        sResult : "検索結果",
        showRoot : "経路を表示",
        showReview : "レビュー"
    },
    {
        restaurant : "Resto",
        cafe : "Cafe",
        bar : "Bar",
        hotel : "Hotel",
        other : "Other",
        check : "Favorites list",
        history : "Street food history",
        root1 : "text: root1",
        root2 : "text: root2",
        root3 : "text: root3",
        search : "search",
        sByText : "Search by text",
        sByHash : "Search by hashtag",
        sByRec : "Recommend",
        sResult : "Search results",
        showRoot : "Show root",
        showReview : "Review"
    }
]

export var radio_l = [
    {
        Udon : "うどん",
        Alcohol : "アルコール",
        Curry : "カレー",
        Coffee : "コーヒー",
        Bread : "パン",
        TakeOut : "持ち帰り",
        Sweets : "スイーツ",
        CNoodle : "冷麺",
        JSweets : "和菓子",
        WSweets : "洋菓子",
        SetMenuMeal : "定食",
        Seafood : "海鮮",
        Ramen : "ラーメン",
        Okonomi : "お好み焼き",
        Steak : "ステーキ",
        FastFood : "ファストフード",
        FamilyRest : "ファミリーレストラン",
        Smoothie : "スムージー",
        Pasta : "パスタ",
        Soba : "そば",
        RiceOmlet : "オムレット",
        ChiniseFood : "中華",
        KoreanBBQ : "焼肉",
        Donut : "ドーナツ",
        Sushi : "寿司",
        SoftDrink : "清涼飲料",
        Hamburger : "ハンバーグ",
        Banquet : "宴会",
        Kushikatsu : "串カツ",
        Specialty : "呉の名物",
        Spanish : "スペイン料理",
        Takoyaki : "たこ焼き",
        Oyster : "牡蠣",
        Oden : "おでん",
        Monjayaki : "もんじゃ焼き",
        FishDishes : "魚料理",
        Yakitori : "焼き鳥",
        Italian : "イタリアン",
        Cake : "ケーキ",
        Sandwich : "サンドウィッチ",
        ShopWithSea : "海の見える店",
        FoodCourt : "フードコート",
        Gyoza : "餃子",
        Pickles : "漬物",
        Tsukudani : "佃煮",
        Earring : "ピアス",
        HomebredChicken : "地鶏",
        FriedChicken : "唐揚げ",
        Stall : "屋台",
        Sashimi : "刺身"
    },
    {
        Udon : "Udon",
        Alcohol : "Alcohol",
        Curry : "Curry",
        Coffee : "Coffee",
        Bread : "Bread",
        TakeOut : "Take out",
        Sweets : "Sweets",
        CNoodle : "Cold noodles",
        JSweets : "Japanese sweets",
        WSweets : "Western confectionery",
        SetMenuMeal : "Set menu meal",
        Seafood : "Seafood",
        Ramen : "Ramen",
        Okonomi : "Okonomiyaki",
        Steak : "Steak",
        FastFood : "Fast food",
        FamilyRest : "Family restaurant",
        Smoothie : "Smoothie",
        Pasta : "Pasta",
        Soba : "Soba",
        RiceOmlet : "Rice Omlet",
        ChiniseFood : "ChiniseFood",
        KoreanBBQ : "Korean barbecue",
        Donut : "Donut",
        Sushi : "Sushi",
        SoftDrink : "Soft Drink",
        Hamburger : "Hamburger steak",
        Banquet : "Banquet",
        Kushikatsu : "Kushikatsu",
        Specialty : "Specialty of Kure",
        Spanish : "Spanish",
        Takoyaki : "Takoyaki",
        Oyster : "Oyster",
        Oden : "Oden",
        Monjayaki : "Monjayaki",
        FishDishes : "Fish dishes",
        Yakitori : "Yakitori",
        Italian : "Italian",
        Cake : "Cake",
        Sandwich : "Sandwich",
        ShopWithSea : "Shop with a view of the sea",
        FoodCourt : "Food Court",
        Gyoza : "Gyoza",
        Pickles : "Pickles",
        Tsukudani : "Food boiled in soy sauce",
        Earring : "Earring",
        HomebredChicken : "Homebred chicken",
        FriedChicken : "Fried chicken",
        Stall : "Stall",
        Sashimi : "Sashimi"
    }
]

export var radio_lng = [
    ["うどん", "アルコール", "カレー", "コーヒー", "パン", "持ち帰り", "スイーツ", "冷麺",
     "和菓子", "洋菓子", "定食", "海鮮", "ラーメン", "お好み焼き", "ステーキ", "ファストフード",
     "ファミリーレストラン", "スムージー", "パスタ", "そば", "オムレット", "中華", "焼肉", 
     "ドーナツ", "寿司", "清涼飲料", "ハンバーグ", "宴会", "串カツ", "呉の名物", "スペイン料理",
     "たこ焼き", "牡蠣", "おでん", "もんじゃ焼き", "魚料理", "焼き鳥", "イタリアン", "ケーキ",
     "サンドウィッチ", "海の見える店", "フードコート", "餃子", "漬物", "佃煮", "ピアス", "地鶏",
     "唐揚げ", "屋台", "刺身"
    ],
    ["Udon", "Alcohol", "Curry", "Coffee", "Bread", "Take out", "Sweets", "Cold noodles",
     "Japanese sweets", "Western confectionery", "Set menu meal", "Seafood", "Ramen",
     "Okonomiyaki", "Steak", "Fast food", "Family restaurant", "Smoothie", "Pasta",
     "Soba", "Rice Omlet", "ChiniseFood", "Korean barbecue", "Donut", "Sushi", "Soft Drink",
     "Hamburger steak", "Banquet", "Kushikatsu", "Specialty of Kure", "Spanish", "Takoyaki",
     "Oyster", "Oden", "Monjayaki", "Fish dishes", "Yakitori", "Italian", "Cake", "Sandwich",
     "Shop with a view of the sea", "Food Court", "Gyoza", "Pickles", "Food boiled in soy sauce",
     "Earring", "Homebred chicken", "Fried chicken", "Stall", "Sashimi"
    ]
]